version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
            name: Install and configure dependencies
            command: |
              git config user.email "ci-build@timetoescape.sk"
              git config user.name "ci-build"
            - run: yarn
            - run: yarn build
            - run: yarn deploy
workflows:
    build-and-test:
      jobs:
        - build-and-test
